---
- name: Check MongoDB service status
  ansible.builtin.command: systemctl status mongodb1 mongodb2 mongodb3
  register: service_status
  failed_when: false
  changed_when: false

- name: Display service status
  ansible.builtin.debug:
    var: service_status.stdout_lines

- name: Check MongoDB log files
  ansible.builtin.command: cat "{{ item }}"
  loop:
    - "/var/log/mongodb/mongod1.log"
    - "/var/log/mongodb/mongod2.log"
    - "/var/log/mongodb/mongod3.log"
  register: mongo_logs
  failed_when: false
  changed_when: false

- name: Temporarily set SELinux to permissive mode
  ansible.builtin.command: setenforce 0
  changed_when: true
  failed_when: false

- name: Fix MongoDB service files
  ansible.builtin.template:
    src: mongodb.service.j2
    dest: "/etc/systemd/system/mongodb{{ item.id }}.service"
    owner: root
    group: root
    mode: "0644"
  loop:
    - { id: "1", port: 27017, config: "/etc/mongodb/mongod1.conf" }
    - { id: "2", port: 27018, config: "/etc/mongodb/mongod2.conf" }
    - { id: "3", port: 27019, config: "/etc/mongodb/mongod3.conf" }

- name: Reload systemd and restart MongoDB services
  ansible.builtin.shell: |
    systemctl daemon-reload
    systemctl restart mongodb1 mongodb2 mongodb3
    systemctl status mongodb1 mongodb2 mongodb3
  register: restart_result
  failed_when: false

- name: Display restart results
  ansible.builtin.debug:
    var: restart_result.stdout_lines